
USE inventorydb;

DROP TABLE IF EXISTS products , orders , users ;

CREATE TABLE products (
    ID  SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    PRICE FLOAT(2) NOT NULL DEFAULT 0.00,
    QUANTITY SMALLINT DEFAULT 0,
    DESCRIPTION TEXT) ENGINE=InnoDB;

CREATE TABLE orders (
    ID SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    TOTAL FLOAT(2) DEFAULT 0.00,
    QUANTITY SMALLINT DEFAULT 0,
    CHECKEDOUT BOOLEAN DEFAULT 0) ENGINE=InnoDB;

CREATE TABLE users (
    ID SMALLINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    PWD VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL DEFAULT "newuser@shop.com",
    IsAdmin BOOLEAN DEFAULT 0) ENGINE=InnoDB;
